
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-provider-pulumi-esc
  namespace: default
  labels:
    app: example-provider-pulumi-esc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-provider-pulumi-esc
  template:
    metadata:
      labels:
        app: example-provider-pulumi-esc
    spec:
      containers:
      - name: client
        image: busybox:latest
        command: ["sh", "-c"]
        env:
        - name: SECRET_FROM_K8S_SECRET
          valueFrom:
            secretKeyRef:
              name: example-provider-secret
              key: password
        args:
        - |
          set -eux
          ls /run/secrets
          find /run/secrets/ -mindepth 1 -maxdepth 1 -not -name '.*' | xargs -t -I {} sh -c 'echo "$(cat "{}")"'
          tail -f /dev/null
        volumeMounts:
        - name: data
          mountPath: /run/secrets
      volumes:
      - name: data
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "example-provider-pulumi-esc"
