apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: example-provider-pulumi-esc
  namespace: default
spec:
  provider: pulumi
  parameters:
    apiUrl: https://api.pulumi.com/api/esc
    organization: dirien
    project: voting-app
    environment: db
    authSecretName: pulumi-secret-provider-auth-credentials
    authSecretNamespace: default
    secrets: |
      - secretPath: "/"
        fileName: "replicas"
        secretKey: postgres.replicas
      
